### ISSUE TITLE
Error on your site

### ISSUE THREAD

**Issue by alexsieusahai** [erikhazzard/VasirEngine#1]
Hey dude,
I just noticed an error on your site for this game and I couldn't find any contact info.
http://vasir.net/blog/game-development/designing-a-browser-based-game-with-d3js-part-1
"My last post explained how to use D3.js to create a fog of war effect like the one I'm using in my game. The battle system is in real time, a sort of mixture between final fantasy and League of Legends."
I click the hyperlink here and I get redirected to:
http://localhost:8130/blog/data-visualization/using-d3-and-svg-filters-to-create-fog-of-war

Cheers!

**Comment by erikhazzard** [comment]
Thanks so much man!
